### ISSUE TITLE
Unauthorized usage of your api

### ISSUE THREAD

**Issue by Quezler** [xmdhs/cursemodownload#11]
Notifying you about the existence of: https://github.com/EnigmaticaModpacks/Enigmatica6/pull/4870

Please consent or disapprove to the usage of your api endpoint for purposes under the enigmatica umbrella, as long as neither option is chosen the endpoint will not be used in production and will stay un-merged until an option that is legally sound is found.

**Comment by xmdhs** [comment]
No problem, but the data is not up to date.

**Comment by Quezler** [comment]
oh? is it cached (updates every = ?) or a snapshot (will never update)?

**Comment by xmdhs** [comment]
snapshot, snapshot of https://addons-ecs.forgesvc.net

**Comment by Quezler** [comment]
allrighty, probably not useful for the checking purpose i had in mind, but i appreciate being allowed to use it regardless :) 👌
