### ISSUE TITLE
Page not found https://gaz492.github.io/TwitchAPI

### ISSUE THREAD

**Issue by z0z0r4** [xmdhs/cursemodownload#8]
```
//From https://gaz492.github.io/TwitchAPI/

var api = `https://addons-ecs.forgesvc.net`
```

**Comment by xmdhs** [comment]
https://gist.github.com/crapStone/9a423f7e97e64a301e88a2f6a0f3e4d9#file-curse_api-md

这里有一部分的 api。事实上，api 是从 curseforge 的客户端上抓包得来的，所以，并没有官方的 api，并且目前所使用的 api 会在将来被 curseforge 所停用。

**Comment by z0z0r4** [comment]
未来会停用，怎么说？
另外自己编译份的话，key需要吗？（写在哪里

**Comment by z0z0r4** [comment]
> https://gist.github.com/crapStone/9a423f7e97e64a301e88a2f6a0f3e4d9#file-curse_api-md
> 
> 这里有一部分的 api。事实上，api 是从 curseforge 的客户端上抓包得来的，所以，并没有官方的文档，并且目前所使用的 api 会在将来被 curseforge 所停用。

我发现，好像https://docs.curseforge.com/可以用？
![image](https://user-images.githubusercontent.com/78744121/161389969-141c5fea-b7e5-4386-87e1-0e785553ba66.png)

**Comment by xmdhs** [comment]
显然我调用的不是一个 api，而且也不需要什么 key
https://mailchi.mp/overwolf/whats-new-with-overwolf-curseforge-november3
